### ISSUE TITLE
Image generation hangs on windows 10

### ISSUE THREAD

**Issue by ammaar8** [plotly/Kaleido#110]
Hey, I'm trying to convert figures into static images but it refuses to work on windows 10. I am using this script for testing - 
```
import plotly.graph_objects as go
import numpy as np
import plotly.io as pio
np.random.seed(1)

N = 100
x = np.random.rand(N)
y = np.random.rand(N)
colors = np.random.rand(N)
sz = np.random.rand(N) * 30

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=x,
    y=y,
    mode="markers",
    marker=go.scatter.Marker(
        size=sz,
        color=colors,
        opacity=0.6,
        colorscale="Viridis"
    )
))

fig.write_image('test.png')
fig.show()

```
It just hangs forever. I tried with both kaleido and orca, same thing. I tried to find out where it was hanging using pycharm and it seems to be this line - https://github.com/plotly/Kaleido/blob/6a46ecae926b4c004bf7232383cf7c74c70748fd/repos/kaleido/py/kaleido/scopes/base.py#L192
If you require anymore info let me know.

**Comment by guilhermebarrett** [comment]
Having the same issue 😢.

**Comment by ammaar8** [comment]
> Having the same issue 😢.

If it's any help, I am now using wsl2 with ubuntu 20 for this. If it doesn't work on localhost, you can host it on `0.0.0.0` and view it on the wsl's ip. Hoping this gets fixed soon since running it on wsl is a lot slower but have no other option.

**Comment by jonmmease** [comment]
If possible, it would be helpful to know if the instructions in this comment produce any additional logging info: https://github.com/plotly/Kaleido/issues/36#issuecomment-756676527

**Comment by ammaar8** [comment]
> If possible, it would be helpful to know if the instructions in this comment produce any additional logging info: [#36 (comment)](https://github.com/plotly/Kaleido/issues/36#issuecomment-756676527)

I tried doing it in cmd and jupyter notebook but it won't interrupt using ctrl+c/interrupt kernel. Any other ideas?

**Comment by jonmmease** [comment]
Ok, thanks for giving that a try.  The next idea is to try to run the kaleido executable CMD, without python.

From python, run this to print out the (long) kaleido launch command

```python
import plotly.io as pio
print(' '.join(pio.kaleido.scope._build_proc_args()))
```

Then run this from the CMD prompt.  If successful, it would print out 

```
{"code": 0, "message": "Success", "result": null, "version": "0.2.1"}
```
along with some benign warnings.  But if it hangs here, it would be great to record what is logged.

**Comment by ammaar8** [comment]
```
[0922/185509.685:WARNING:resource_bundle.cc(405)] locale_file_path.empty() for locale
[0922/185509.743:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.
{"code": 0, "message": "Success", "result": null, "version": "0.2.1"}
[0922/185510.510:ERROR:gpu_init.cc(430)] Passthrough is not supported, GL is swiftshader
```

Sorry about the late reply, this is what I get.

**Comment by leeTimothy** [comment]
+1 for similar issue with similar output as above

**Comment by jonmmease** [comment]
Ok, thanks @ammaar8 and @leeTimothy. That's helpful.

It's possible that the key error is
```
[0922/185510.510:ERROR:gpu_init.cc(430)] Passthrough is not supported, GL is swiftshader
```
Although the `{"code: 0,...}` line indicates that kaleido did launch successfully. 

After running that first command, could you try pasting the following content into the console and pressing Enter:
```
{"data":{"layout": {}}, "format":"svg"}
```
This is an actual image export request, and if successful would print out an SVG string.  Again, it would be helpful to know if this prints out any warnings or errors, or if it hangs.

Thanks!

**Comment by leeTimothy** [comment]
this might be where the behaviour im experiencing might deviate from @ammaar8

although running the output of 
```
import plotly.io as pio
print(' '.join(pio.kaleido.scope._build_proc_args()))
```

provides a very similar trace like ammaar
```
[0924/131936.214:WARNING:resource_bundle.cc(405)] locale_file_path.empty() for locale 
[0924/131936.234:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.
{"code": 0, "message": "Success", "result": null, "version": "0.2.1"}
[0924/131936.291:ERROR:gpu_init.cc(430)] Passthrough is not supported, GL is swiftshader
```

the command itself never runs to completion and just hangs there.

if the behaviour deviates - please let me know if you want me to raise this separately.

cheers

**Comment by jonmmease** [comment]
@leeTimothy, the first command is intended to stay running and wait for image export requests.  Did you try pasting the JSON snippet I described above and hitting enter?  It would be good to know if this hangs, or if any additional info is logged.
Thanks!

**Comment by leeTimothy** [comment]
Ah apologies!

Please see below.

```
{"data":{"layout": {}}, "format":"svg"}
{"code": 1, "message": "Failed to serialize document: Uncaught", "result": null, "version": "0.2.1"}
```

**Comment by jonmmease** [comment]
Ok, thanks @leeTimothy.

Here are a couple of experiments to try.  The long kaleido command has a bunch of chromium flags. e.g. one of them is `--disable-gpu`.   

1. Try deleting the `--disable-gpu` flag, and performing the test process again.
2. Try adding the `--disable-webgl` flag.

If you, or anyone else, is interested in experimenting more with chromium options. Here's a giant list of the available chromium flags: https://peter.sh/experiments/chromium-command-line-switches/.

**Comment by ammaar8** [comment]
Hey @leeTimothy,

Sorry for the late reply, I'm on 19043.1237 like you are!

**Comment by jonmmease** [comment]
That version info helps a lot, thanks for investigating @leeTimothy and @ammaar8

**Comment by RyanChapman2x** [comment]
Just to add: I have three Windows 10 machines. Two work, these are builds 18363 and 19041. One machine freezes the exact way as described by everyone in this issue, build 19042.

**Comment by stroitzsch** [comment]
I'm seemingly having the same issue on Windows 10 Build 19043.1320.

Has anyone figured out a workaround for this?

**Comment by lordee** [comment]
I changed back to the other engine (orca?)

**Comment by amarhod** [comment]
> I'm seemingly having the same issue on Windows 10 Build 19043.1320.
> 
> Has anyone figured out a workaround for this?

It works with WSL for me

**Comment by manujosephv** [comment]
I have the exact same issue. downgrading `kaleido` to `0.1.0` solved it for me.

**Comment by michaeloliverx** [comment]
I am also having this issue on Windows 10 Build: 19043.1348.

`write_image` will hang forever and cannot be killed with <kbd>Ctrl</kbd>+<kbd>C</kbd>.

**Comment by mshakib** [comment]
I hope you find this helpful
I was able to resolve the issue by downgrade Kaleido to 0.1.0 and ﻿Configuring the Kaleido library to see the path for the Kaleido executable.
here is the change that I made to the Kaleido library:

﻿file: ﻿Kaleido\scope\base.py ﻿
﻿Line:70

```

  @classmethod
  def executable_path(cls):
      vendored_executable_path = os.path.join(
          os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
          'executable',
          'kaleido.cmd'
  
      )
    
```

**Comment by jglascock** [comment]
I had the same result at @StSchulze ...downgrading to kaleido to 0.1.0post1 worked without any issues.

**Comment by koushikam** [comment]
I have the same issue on windows 10. Downgrading to 0.1.0 didn't resolve the issue.

**Comment by Prajval-1608** [comment]
Please note downgrading to 0.1.0 doesn't work. Downgrading to 0.1.0post1 DOES WORK.

**Comment by tchannagiri** [comment]
Thanks for the tips. I can confirm that kaleido 0.1.0post1 works but not the current latest (0.2.1). I haven't tried 0.1.0.

**Comment by mherrmann3** [comment]
Same problem here (Windows 10 build 19044.1586).
_[conda-forge](https://anaconda.org/conda-forge/python-kaleido/files)_ doesn't have a `0.1.0post1` , but its provided `0.1.0` solved the issue also for me (provided _conda-forge_ is your preferred channel):
```
conda install python-kaleido=0.1.0
```

**Comment by j-k-f** [comment]
Same problem here, 
windows: 10.0.19042 Build 19042
Ran install for kaleido 0.1.0post1 in terminal fixed for me as well.
`pip install kaleido==0.1.0post1`

**Comment by josetduarte** [comment]
Had the same problem, kaleido version 0.1.0post1 fixed the issue

**Comment by ThijsvZ** [comment]
Windows 10 home, version 21H2, build 19044.1766
VS code 1.67.2.
conda 4.13.0
plotly 5.8.2
python 3.10.5

Kaleido 0.2.1. produces the hang, `conda install python-kaleido=0.1.0` works perfectly.

**Comment by ddespina** [comment]
I had the same issue in pycharm, conda env. The downgrade to Kaleido 0.1.0 didin't work. But the downgrade to 0.1.0post1 worked (I have win 10 build 19044)

**Comment by mherrmann3** [comment]
Does anyone have an idea why this happens? Here one reason why this downgrade my be undesired:

I noticed that `v0.1.0`(`post1`) and `v0.2.1` do not produce the exact same PDF files because the fonts are slightly different:

- `v0.1.0` uses [Postscript Type 3](https://en.wikipedia.org/wiki/PostScript_fonts#Type_3) font
- `v0.2.1` uses [OpenSans](https://en.wikipedia.org/wiki/Open_Sans) (as does plotly by default)

Strangely, the fonts in the PNGs do not differ that much, they're almost identical.
I would judge the PDFs of `v0.2.1` to be more similar to the PNGs.

I guess this font difference is related to the upgrade of the Chromium library in `v0.2.0`, because the Skia PDF versions are different (in the _PDF producer_ field):
- `v0.1.0`: `Skia/PDF m83`
- `v0.2.0` `Skia/PDF m91`

Hence, the proposed solution of downgrading Kaleido is not beneficial for reproducibility and consistency b/w PDFs and PNG.

**Comment by whaleprince** [comment]
> ```python
> import plotly.io as pio
> print(' '.join(pio.kaleido.scope._build_proc_args()))
> ```
my output is 
normal code
D:\ProgramData\Anaconda3\lib\site-packages\kaleido\executable\kaleido.cmd plotly --plotlyjs='D:\\ProgramData\\Anaconda3\\lib\\site-packages\\plotly\\package_data\\plotly.min.js' --mathjax='file:///D:/ProgramData/Anaconda3/lib/site-packages/kaleido/executable/etc/mathjax/MathJax.js' --disable-gpu --allow-file-access-from-files --disable-breakpad --disable-dev-shm-usage --no-sandbox

problem code
/home/python/software/Python-3.8.8/lib/python3.8/site-packages/kaleido/executable/kaleido plotly --plotlyjs='/home/python/software/Python-3.8.8/lib/python3.8/site-packages/plotly/package_data/plotly.min.js' --mathjax='file:///home/python/software/Python-3.8.8/lib/python3.8/site-packages/kaleido/executable/etc/mathjax/MathJax.js' --disable-gpu --allow-file-access-from-files --disable-breakpad --disable-dev-shm-usage --no-sandbox

**Comment by ronak1009** [comment]
I am also facing the same issue on Windows 10 and centos7 with Python 3.9
```python
import plotly.io as pio
print(' '.join(pio.kaleido.scope._build_proc_args()))
```
Output for the following command to get the full command of the kaleido executable is:
```
C:\Python\Python39\lib\site-packages\kaleido\executable\kaleido.cmd plotly --plotlyjs='C:\\Python\\Python39\\lib\\site-packages\\plotly\\package_data\\plotly.min.js' --mathjax='file:///C:/Python/Python39/lib/site-packages/kaleido/executable/etc/mathjax/MathJax.js' --allow-file-access-from-files --disable-breakpad --disable-dev-shm-usage --no-
sandbox --disable-webgl
```

And console output to this is:
```
[1118/165643.734:WARNING:resource_bundle.cc(405)] locale_file_path.empty() for locale
[1118/165643.761:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.
{"code": 0, "message": "Success", "result": null, "version": "0.2.1"}
[1118/165643.817:ERROR:gpu_init.cc(430)] Passthrough is not supported, GL is swiftshader
[1118/165643.832:ERROR:command_buffer_proxy_impl.cc(121)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
```

Note: I could not paste JSON mentioned above.

My env:
Python 3.9.13
plotly==5.10.0
kaleido==0.2.1

**Comment by Hoernchen** [comment]
Same issue here, this can easily be fixed by downgrading kaleido
` pip install --upgrade "kaleido==0.1.*"`

- the problem is that this is not obvious, plotly itself is a dependency of the package I am actually using, and some weird unmaintained kaleido backend thing getting stuck is.. unexpected.

**Comment by michaeloliverx** [comment]
Anyone using Poetry might find this useful, only installs the old version if the platform is Windows:
```toml
kaleido = [
    # Newest version hangs on Windows, see https://github.com/plotly/Kaleido/issues/110
    {version = "0.1.0post1", markers = "platform_system == 'Windows'" }, 
    {version = "0.2.1", markers = "platform_system != 'Windows'"}
]
```

**Comment by stanos4** [comment]
any other work-arounds besides downgrading to kaleido 0.1.0post1? I'm on w11 machine, 22000.1455, have the same issue. Problem with downgrade is that you're unable to export images of large plots - i'm particularly speaking about ~30 million points heatmap, currently with many NaN points.

https://github.com/plotly/Kaleido/issues/19

**Comment by AmedBrook** [comment]
same issue , downgrading to kaleido=0.1.0 works for me on windows 11

**Comment by TheNoneMan** [comment]
Same issue, Windows 10 19044.2846
While investigating and following this thread discovered that CMD immediately closes for my particular user, meanwhile I was working from powershell just fine.
Managed to resolve this by deleting registry entry 

> **HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor**

Afterward, CMD started launching fine as well as Kaleido subprocess. I assume it is because Kaleido is being launched via  Subprocess library with `shell=True` and its readiness is assumed based on console output, specifically json line

> {"code: 0,...}

And since CMD wasn't launching normally, there wasn't any output, any json to assume Kaleido readiness.

**Comment by hhaensel** [comment]
Retried to reproduce the error today but the issue seems to have disappeared on my updated Windows 11 and Windows 10 machines.

**Comment by amks1** [comment]
I got the same issue in Windows 11.

**Comment by MaartenBW** [comment]
I still have this issue on Windows 11 with kaleido 0.2.1.

0.2.1.post1 is for some reason niet available for my platform (windows 11, 64-bit processor, python 3.11)

**Comment by szmcdull** [comment]
Sad for such a long time no one is fixing this

**Comment by ant1j** [comment]
Looks like I am not the only one having an issue with `kaleido` on Windows.

The culprit seems to be the `--no-sandbox` options when starting Chromium.

I used the snippet:
```
import plotly.io as pio
print(' '.join(pio.kaleido.scope._build_proc_args()))
```

Launching as is never displays the line with json (`{"code": 0 ...}`)
Launching after removing the arg `--no-sandbox` display the JSON.

The option was added here: https://github.com/plotly/Kaleido/blame/master/repos/kaleido/py/kaleido/scopes/plotly.py#L16
I have no idea what is the Chromium sandbox and why Kaleido should run without it? 

So if we want to remove this from the options, we need to change this line.

I guess it boils down to: 
1. why Kaleido needs the `--no-sandbox`,
2. it is safe to run without the option / with the sandbox (the few lines I wrote on the topic is that no sandbox loosen the security...)

**Comment by neuropathbasel** [comment]
After about 2 years of encountering this issue (plotly stalls or gets an error when writing plots to PNG on some computers I use, but not all) I found a solution. This does not seem to be linked to particular kaleido/plotly version combinations but essentially boils down to headless (or sort of headless) systems.

kaleido (based on chromium, as I understood) can be launched with command line arguments that make it ignore GPU support, physical  or xsever screens etc. However, these command line options need to be passed to kaleido from plotly.
Here is how (e.g., WLS, Windows 10, Ubuntu 20.04, python 3.7, kaleido==0.2.1, plotly==5.3.1):

I got the idea here:  https://discuss.streamlit.io/t/unable-to-run-plotly-kaleido-on-streamlit-cloud-to-generate-image-exports-from-graphs/23425/6

You can test this in Jupyer notebook:
```
import kaleido
import plotly.express as px
import plotly.io as pio

# set explicit headless parameters for chromium (not sure if all are needed)
pio.kaleido.scope.chromium_args = (
    "--headless",
    "--no-sandbox",
    "--single-process",
    "--disable-gpu"
)  # tuple with chromium args

fig = px.scatter(x=[0, 1, 2, 3, 4], y=[0, 1, 4, 9, 16])
fig.show()
fig.write_html('first_figure.html', auto_open=False)
fig.write_image('first_figure.png') # fails with kaleido 0.1.0, 0.2.1

# https://github.com/plotly/Kaleido/issues/134
```

Here's what happens behind the scenes:

1. plotly calls kaleido
2. kaleido binary starts, headless paremeters not set
3. kaleido crashes
4. plotly waits indefinitely for kaleido to respond, which will never happen (like here https://github.com/plotly/Kaleido/issues/134)

If you launch the kaleido binary (e.g. from ... /lib/python/site-packages.... /kaleido on a headless system (like WSL, which is formally headless) , you will see a crash:
```
3f)
  r8: 0000000000000000  r9: 00007fffec0c87c0 r10: 0000000000000008 r11: 0000000000000008
 r12: 00007fffec0c9260 r13: 00007fffec0c9ad0 r14: 00007fffec0c9ae0 r15: 00007fffec0c9ae8
  di: 0000000000000002  si: 00007fffec0c87c0  bp: 00007fffec0c8a10  bx: 00007f0f7eee0e00
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000008  sp: 00007fffec0c87c0
  ip: 00007f0f7f36300b efl: 0000000000000246 cgf: 00000053002b0033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```
If you launch kaleido on the same headless system with above-mentioned command line arguments, it runs perfectly fine:
```
 ./kaleido --headless --no-sandbox --single-process --disable-gpu
[0515/220312.534508:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale
[0515/220312.616704:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale
[0515/220312.652037:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale
{"code": 1, "message": "No Scope Specified", "result": null, "version": "0.2.1"}
```
I'm not sure that these is a simple explanation why some version combinations of plotly and kaleido fixed the issue. I tried all of these suggestions (without success) before I encountered above-mentioned fix. And there is a logical explanation to it.

**Comment by neuropathbasel** [comment]
I outcommented the `--no-sandbox`  option. It can lead up to orphaned kaleido processes as I just found out. These keep running after completing their task. And the option is not required to make it work.

**Comment by ant1j** [comment]
@neuropathbasel Do you confirm it works for WSL but not Windows 11 natively?
Just tried on W11, Python `3.11.7`, `kaleido==0.2.1`, but I got an error message (better than hanging forever though)

**Comment by sgbaird** [comment]
> @neuropathbasel Do you confirm it works for WSL but not Windows 11 natively? Just tried on W11, Python `3.11.7`, `kaleido==0.2.1`, but I got an error message (better than hanging forever though)

```
Exception has occurred: ValueError
Failed to start Kaleido subprocess. Error stream:

[0529/145805.700:WARNING:resource_bundle.cc(405)] locale_file_path.empty() for locale 
[0529/145805.724:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.
[0529/145805.730:ERROR:dxva_video_decode_accelerator_win.cc(1405)] DXVAVDA fatal error: Could not load mf.dll: The specified module could not be found. (0x7E)
  File "C:\Users\sterg\Documents\GitHub\ACC-HelloWorld\6-connecting-the-pieces-sgbaird\orchestrator.py", line 337, in <module>
    fig.write_image(image_name)
ValueError: Failed to start Kaleido subprocess. Error stream:

[0529/145805.700:WARNING:resource_bundle.cc(405)] locale_file_path.empty() for locale 
[0529/145805.724:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.
[0529/145805.730:ERROR:dxva_video_decode_accelerator_win.cc(1405)] DXVAVDA fatal error: Could not load mf.dll: The specified module could not be found. (0x7E)
```

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson

**Comment by Walter-Reactor** [comment]
Hit this issue, native windows 11. Downgrading to `0.1.0post1` fixed it for me

**Comment by TheSecMaven** [comment]
very stupid. do better, same issue and @Walter-Reactor solution fixed.

**Comment by ayjayt** [comment]
hi! I'm just seeing this. There is in fact a release candidate for the next version of kaleido on pypi and plan is to make it an official version this week, just dealing with some annoying platform issues. Will put this issue on watch for further activity.

**Comment by TheSecMaven** [comment]
Adjusted now that I am out of the frustrated state of code not working haha. 

I do apologize, and thank you for pointing it out.

**Comment by maximweb** [comment]
I've had trouble with exporting/streaming figures to svg on Windows 10 and 11 as well, with the process just running indefinitely. As suggested here, I've been using `kaleido==0.1.0.post1` in the meantime.

Today, I tested kaledio versions 0.4.0.rc3 and 1.0.0.rc0 with python 3.10.11 as well as 3.12.0, in the hopes for a change.

Unfortunately, they **still hang forever**.

Maybe the following report helps to narrow it down?

PS: Not sure whether to post it here ore in #223 


**System**: Windows 11, VSCode 1.95.3 (Notebook)

**Test code**

```
import os
import plotly.graph_objects as go

os.environ["KALEIDO_DEBUG"] = "1"

fig = go.Figure()

fig.add_annotation(
    x=0.5,
    y=0.5,
    xref="paper",
    yref="paper",
    text="Hello World",
    showarrow=False,
    font=dict(size=12, color="#ff0000"),
)

fig.write_image("test_kaleido.svg")
fig.show()
```

**Output before hanging forever (python 3.12.0, kaleido 1.0.0.rc0)**

```
Tempdir: C:\Users\<REDACTED>\AppData\Local\Temp\tmp1mn_17ho
************Displaying generated HTML*************
<!DOCTYPE html>
<html>
  <head>
    <style id="head-style"></style>
    <title>Kaleido-fier</title>
    <script>
        window.KaleidoReport = ["start"];
        function logError(e) {
            window.KaleidoReport.push("error");
            window.KaleidoReport.push(e);
            if (!navigator.onLine) {
                window.KaleidoReport.push("offline");
            }
        }
    </script>
    <script>
      window.PlotlyConfig = {MathJaxConfig: 'local'}
    </script>
 <script src="https://cdn.plot.ly/plotly-2.35.2.min.js" charset="utf-8" onerror="logError('plotly')"></script>
 <script type="text/javascript" id="MathJax-script" src="file:///c:/Users/<REDACTED>/envs/<REDACTED>/Lib/site-packages/kaleido/vendor/mathjax/MathJax.js?config=TeX-AMS-MML_SVG" onerror="logError('mathjax')"></script>
    <script src="file:///c:/Users/<REDACTED>/envs/<REDACTED>/Lib/site-packages/kaleido/vendor/kaleido_scopes.js" onerror="logError('scoper')"></script>  </head>
  <body style="{margin: 0; padding: 0;}"><img id="kaleido-image"><img></body>
</html>
***********************end************************
************Displaying generated HTML*************
<!DOCTYPE html>
<html>
  <head>
    <style id="head-style"></style>
    <title>Kaleido-fier</title>
    <script>
        window.KaleidoReport = ["start"];
        function logError(e) {
            window.KaleidoReport.push("error");
            window.KaleidoReport.push(e);
            if (!navigator.onLine) {
                window.KaleidoReport.push("offline");
            }
        }
    </script>
    <script>
      window.PlotlyConfig = {MathJaxConfig: 'local'}
    </script>
 <script src="file:///c:/Users/<REDACTED>/envs/<REDACTED>/Lib/site-packages/plotly/package_data/plotly.min.js" charset="utf-8" onerror="logError('plotly')"></script>
 <script type="text/javascript" id="MathJax-script" src="file:///c:/Users/<REDACTED>/envs/<REDACTED>/Lib/site-packages/kaleido/vendor/mathjax/MathJax.js?config=TeX-AMS-MML_SVG" onerror="logError('mathjax')"></script>
    <script src="file:///c:/Users/<REDACTED>/envs/<REDACTED>/Lib/site-packages/kaleido/vendor/kaleido_scopes.js" onerror="logError('scoper')"></script>  </head>
  <body style="{margin: 0; padding: 0;}"><img id="kaleido-image"><img></body>
</html>
***********************end************************
Got running loop, threading
Calling thread start
Calling to_image in thread
c:\Users\<REDACTED>\envs\<REDACTED>\Lib\site-packages\choreographer\browser.py:85: UserWarning:

A value has been passed to debug_browser which is not compatible with python. The default value if deug_browser is True is whatever the value of sys.stderr is. sys.stderr may be many things but debug_browser must be a value Popen accepts for stderr, or True.

STDERR: <ipykernel.iostream.OutStream object at 0x0000021B9FBEB6D0>
TEMP DIR NAME: C:\Users\<REDACTED>\AppData\Local\Temp\tmp9h8jc2d9
DEBUG REPORT:
BROWSER_PATH: C:\Program Files\Google\Chrome\Application\chrome.exe
USER_DATA_DIR: C:\Users\<REDACTED>\AppData\Local\Temp\tmp9h8jc2d9
We are in a selector event loop, use loop_hack
read_jsons (blocking):
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Browser._open_async() done, defined at c:\Users\<REDACTED>\envs\<REDACTED>\Lib\site-packages\choreographer\browser.py:246> exception=UnsupportedOperation('fileno')>
Traceback (most recent call last):
  File "c:\Users\<REDACTED>\envs\<REDACTED>\Lib\site-packages\choreographer\browser.py", line 264, in _open_async
    self.subprocess = await open_browser(to_chromium=self.pipe.read_to_chromium,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\<REDACTED>\envs\<REDACTED>\Lib\site-packages\choreographer\chrome_wrapper.py", line 76, in run
    return subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 992, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1406, in _get_handles
    errwrite = msvcrt.get_osfhandle(stderr.fileno())
                                    ^^^^^^^^^^^^^^^
  File "c:\Users\<REDACTED>\envs\<REDACTED>\Lib\site-packages\ipykernel\iostream.py", line 371, in fileno
    raise io.UnsupportedOperation(msg)
io.UnsupportedOperation: fileno
```

**Comment by mattiatantardini** [comment]
Still having the freeze problem, the code hangs indefinitely when the `write_image` command is hit. Google Chrome is installed in the system, under `/usr/bin/google-chrome`, which is one of the folder that the [plotly documentation](https://plotly.com/python/static-image-export/#additional-information-on-browsers-with-kaleido) says that kailedo looks into.

Python 3.12.13, kaleido 1.3.0 and plotly 6.8.0.

Tried also to downgrade to `kaleido==1.0..0rc13` and `plotly==6.1.1` as suggested [here](https://github.com/plotly/Kaleido/issues/322#issuecomment-2901708669), to no avail.
