### ISSUE TITLE
ValueError: Failed to start Kaleido subprocess.

### ISSUE THREAD

**Issue by Yovoss** [plotly/Kaleido#130]
I use conda-pack command to remove my gru conda environment from server A to server B, and there is an error about kaleido while i use the fig.write_image(). The error message is as follows:

**

> Traceback (most recent call last):
>   File "5_hyperparameter_tuner_HMMEF_optuna.py", line 419, in <module>
>     fig.write_image(os.path.join(output_path, "optimization_history({}).png".format(LABEL_DICT[str(ARGS.label)])))
>   File "/home/zju/anaconda3/envs/gru/lib/python3.6/site-packages/plotly/basedatatypes.py", line 3806, in write_image
>     return pio.write_image(self, *args, **kwargs)
>   File "/home/zju/anaconda3/envs/gru/lib/python3.6/site-packages/plotly/io/_kaleido.py", line 252, in write_image
>     engine=engine,
>   File "/home/zju/anaconda3/envs/gru/lib/python3.6/site-packages/plotly/io/_kaleido.py", line 132, in to_image
>     fig_dict, format=format, width=width, height=height, scale=scale
>   File "/home/zju/anaconda3/envs/gru/lib/python3.6/site-packages/kaleido/scopes/plotly.py", line 154, in transform
>     figure, format=format, width=width, height=height, scale=scale
>   File "/home/zju/anaconda3/envs/gru/lib/python3.6/site-packages/kaleido/scopes/base.py", line 293, in _perform_transform
>     self._ensure_kaleido()
>   File "/home/zju/anaconda3/envs/gru/lib/python3.6/site-packages/kaleido/scopes/base.py", line 198, in _ensure_kaleido
>     raise ValueError(message)
> ValueError: Failed to start Kaleido subprocess. Error stream:
> 
> /home/zju/anaconda3/envs/gru/bin/kaleido: line 3: /home/conda/feedstock_root/build_artifacts/kaleido-core_1615199303525/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/KaleidoApp/kaleido: No such file or directory

**

So i want to know how to fix it? and the import is normal.
![image](https://user-images.githubusercontent.com/30063890/159627581-b901ec6c-b010-4698-b8f6-671d9b780ccc.png)

**Comment by mikeylinton** [comment]
Hi, wanted to add that I also am having the same issue

```
ValueError: Failed to start Kaleido subprocess. Error stream:

[0406/024334.965007:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale 
prctl(PR_SET_NO_NEW_PRIVS) failed
[0406/024335.025482:FATAL:zygote_communication_linux.cc(255)] Cannot communicate with zygote
#0 0x55f266e5bd79 base::debug::CollectStackTrace()
#1 0x55f266dd9633 base::debug::StackTrace::StackTrace()
#2 0x55f266de915f logging::LogMessage::~LogMessage()
#3 0x55f265585d85 content::ZygoteCommunication::Init()
#4 0x55f2655863c7 content::CreateUnsandboxedZygote()
#5 0x55f266b4280b content::ContentMainRunnerImpl::Initialize()
#6 0x55f266b40bbc content::RunContentProcess()
#7 0x55f266b40cfc content::ContentMain()
#8 0x55f266b92182 headless::(anonymous namespace)::RunContentMain()
#9 0x55f266b92025 headless::HeadlessBrowserMain()
#10 0x55f264bb0fa8 main
#11 0x7f82aaf6e0ba __libc_start_main
#12 0x55f264baa3ea _start

Received signal 6
#0 0x55f266e5bd79 base::debug::CollectStackTrace()
#1 0x55f266dd9633 base::debug::StackTrace::StackTrace()
#2 0x55f266e5b95b base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f82ac4437e0 (/usr/lib64/libpthread-2.26.so+0x117df)
#4 0x7f82aaf80c20 __GI_raise
#5 0x7f82aaf820c8 __GI_abort
#6 0x55f266e5a8f5 base::debug::BreakDebugger()
#7 0x55f266de95b2 logging::LogMessage::~LogMessage()
#8 0x55f265585d85 content::ZygoteCommunication::Init()
#9 0x55f2655863c7 content::CreateUnsandboxedZygote()
#10 0x55f266b4280b content::ContentMainRunnerImpl::Initialize()
#11 0x55f266b40bbc content::RunContentProcess()
#12 0x55f266b40cfc content::ContentMain()
#13 0x55f266b92182 headless::(anonymous namespace)::RunContentMain()
#14 0x55f266b92025 headless::HeadlessBrowserMain()
#15 0x55f264bb0fa8 main
#16 0x7f82aaf6e0ba __libc_start_main
#17 0x55f264baa3ea _start
  r8: 0000000000000000  r9: 00007ffec14e5460 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffec14e5f00 r13: 00007ffec14e67f0 r14: 00007ffec14e6800 r15: 00007ffec14e6808
  di: 0000000000000002  si: 00007ffec14e5460  bp: 00007ffec14e56b0  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f82aaf80c20  sp: 00007ffec14e5460
  ip: 00007f82aaf80c20 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

The version of kaleido is also 0.2.1

**Comment by mikeylinton** [comment]
@Yovoss please put the bug label on this issue.

**Comment by rshkv** [comment]
@Yovoss, I think you need to run `./gru/bin/conda-unpack` on server B.

**Comment by allanelder** [comment]
> Hi, wanted to add that I also am having the same issue
> 
> ```
> ValueError: Failed to start Kaleido subprocess. Error stream:
> 
> [0406/024334.965007:WARNING:resource_bundle.cc(431)] locale_file_path.empty() for locale 
> prctl(PR_SET_NO_NEW_PRIVS) failed
> [0406/024335.025482:FATAL:zygote_communication_linux.cc(255)] Cannot communicate with zygote
> #0 0x55f266e5bd79 base::debug::CollectStackTrace()
> #1 0x55f266dd9633 base::debug::StackTrace::StackTrace()
> #2 0x55f266de915f logging::LogMessage::~LogMessage()
> #3 0x55f265585d85 content::ZygoteCommunication::Init()
> #4 0x55f2655863c7 content::CreateUnsandboxedZygote()
> #5 0x55f266b4280b content::ContentMainRunnerImpl::Initialize()
> #6 0x55f266b40bbc content::RunContentProcess()
> #7 0x55f266b40cfc content::ContentMain()
> #8 0x55f266b92182 headless::(anonymous namespace)::RunContentMain()
> #9 0x55f266b92025 headless::HeadlessBrowserMain()
> #10 0x55f264bb0fa8 main
> #11 0x7f82aaf6e0ba __libc_start_main
> #12 0x55f264baa3ea _start
> 
> Received signal 6
> #0 0x55f266e5bd79 base::debug::CollectStackTrace()
> #1 0x55f266dd9633 base::debug::StackTrace::StackTrace()
> #2 0x55f266e5b95b base::debug::(anonymous namespace)::StackDumpSignalHandler()
> #3 0x7f82ac4437e0 (/usr/lib64/libpthread-2.26.so+0x117df)
> #4 0x7f82aaf80c20 __GI_raise
> #5 0x7f82aaf820c8 __GI_abort
> #6 0x55f266e5a8f5 base::debug::BreakDebugger()
> #7 0x55f266de95b2 logging::LogMessage::~LogMessage()
> #8 0x55f265585d85 content::ZygoteCommunication::Init()
> #9 0x55f2655863c7 content::CreateUnsandboxedZygote()
> #10 0x55f266b4280b content::ContentMainRunnerImpl::Initialize()
> #11 0x55f266b40bbc content::RunContentProcess()
> #12 0x55f266b40cfc content::ContentMain()
> #13 0x55f266b92182 headless::(anonymous namespace)::RunContentMain()
> #14 0x55f266b92025 headless::HeadlessBrowserMain()
> #15 0x55f264bb0fa8 main
> #16 0x7f82aaf6e0ba __libc_start_main
> #17 0x55f264baa3ea _start
>   r8: 0000000000000000  r9: 00007ffec14e5460 r10: 0000000000000008 r11: 0000000000000246
>  r12: 00007ffec14e5f00 r13: 00007ffec14e67f0 r14: 00007ffec14e6800 r15: 00007ffec14e6808
>   di: 0000000000000002  si: 00007ffec14e5460  bp: 00007ffec14e56b0  bx: 0000000000000006
>   dx: 0000000000000000  ax: 0000000000000000  cx: 00007f82aaf80c20  sp: 00007ffec14e5460
>   ip: 00007f82aaf80c20 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
>  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> ```
> 
> The version of kaleido is also 0.2.1

I'm having this same issue - running on a docker container on AWS Lambda. Just doing a write_image from a plotly figure, have tried setting --single-process that I saw suggested elsewhere as a potential fix on Lambda.

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson

**Comment by t-soehngen** [comment]
I had the same issue as Yovoss in a micromamba environment with both kaleido 0.2.1 and 0.1.0. What helped in my case was removing kaleido via micromamba and installing it in the env using pip (kaleido 0.2.1). This was on an centOS HPC with plotly 5.24.1 and python 3.12.8.
Hope that helps someone else.

**Comment by ayjayt** [comment]
There's nothing to do here since this all now legacy, so I'm closing the issue. Good in case someone pinned the old issue.
