### ISSUE TITLE
Failed to start Kaleido subprocess on windowsserver 2019-datacenter-core

### ISSUE THREAD

**Issue by DrewScoggins** [plotly/Kaleido#136]
I am getting the below stack trace when I try and call write_image on VMs that are running windowsserver 2019-datacenter-core. This command has always worked before on a normal version of Windows, so I was wondering if it had something to do with the more limited install of this version of Windows. As can also be seen, I am not getting anything in the error stream.

```
Traceback (most recent call last):
  File "D:\Users\batch-explorer-user\Documents\test.py", line 24, in <module>
    fig.write_image("test.png")
  File "D:\batch\tasks\shared\Python\lib\site-packages\plotly\basedatatypes.py", line 3831, in write_image
    return pio.write_image(self, *args, **kwargs)
  File "D:\batch\tasks\shared\Python\lib\site-packages\plotly\io\_kaleido.py", line 268, in write_image
    img_data = to_image(
  File "D:\batch\tasks\shared\Python\lib\site-packages\plotly\io\_kaleido.py", line 145, in to_image
    img_bytes = scope.transform(
  File "D:\batch\tasks\shared\Python\lib\site-packages\kaleido\scopes\plotly.py", line 153, in transform
    response = self._perform_transform(
  File "D:\batch\tasks\shared\Python\lib\site-packages\kaleido\scopes\base.py", line 293, in _perform_transform
    self._ensure_kaleido()
  File "D:\batch\tasks\shared\Python\lib\site-packages\kaleido\scopes\base.py", line 198, in _ensure_kaleido
    raise ValueError(message)
ValueError: Failed to start Kaleido subprocess. Error stream:
```

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson

**Comment by DrewScoggins** [comment]
Thanks for the response. We ended up just running on a bigger version of Windows, but if there is eventually a fix for this that would be great.
