### ISSUE TITLE
Can't install using poetry on Windows 11 Python 3.11

### ISSUE THREAD

**Issue by SergeyHein** [plotly/Kaleido#176]
Can't install using poetry on Windows 11 Python 3.11

```powershell

PS .......> poetry add kaleido 
Using version ^0.2.1.post1 for kaleido

Updating dependencies
Resolving dependencies... (0.5s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing kaleido (0.2.1.post1): Failed

  RuntimeError

  Unable to find installation candidates for kaleido (0.2.1.post1)

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chooser.py:74 in choose_for
       70│
       71│             links.append(link)
       72│
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│

Cannot install kaleido.

.......> 
```

**Comment by tvdboom** [comment]
I am having the same issue with [pdm](https://pdm-project.org/latest/)

```
Synchronizing working set with resolved packages: 0 to add, 1 to update, 0 to remove                                                                                                                                                                                                                                  

  ✖ Update kaleido 0.2.1 -> 0.2.1.post1 failed
Retry failed jobs
  ✖ Update kaleido 0.2.1 -> 0.2.1.post1 failed

ERRORS:
update kaleido failed:
Traceback (most recent call last):
  File "C:\Users\Mavs\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mavs\Documents\Python\ATOM\venv311\Lib\site-packages\pdm\installers\synchronizers.py", line 303, in update_candidate
    self.manager.overwrite(dist, can)
  File "C:\Users\Mavs\Documents\Python\ATOM\venv311\Lib\site-packages\pdm\installers\manager.py", line 55, in overwrite
    installed = self.install(candidate)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mavs\Documents\Python\ATOM\venv311\Lib\site-packages\pdm\installers\manager.py", line 30, in install
    prepared.get_cached_package(), self.environment, prepared.direct_url(), self.use_install_cache
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mavs\Documents\Python\ATOM\venv311\Lib\site-packages\pdm\models\candidates.py", line 404, in get_cached_package
    self._obtain(allow_all=False)
  File "C:\Users\Mavs\Documents\Python\ATOM\venv311\Lib\site-packages\pdm\models\candidates.py", line 466, in _obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `kaleido` that matches the environment or hashes
```

**Comment by alexdashkov** [comment]
I have the same problem with poetry on the mac m1 in a debian docker image with python 3.12. However I can install version `0.2.1`

**Comment by gvwilson** [comment]
Thanks for your interest in Kaleido. We are currently working on an overhaul that might address your issue - we hope to have news in a few weeks and will post an update then. Thanks - @gvwilson

**Comment by zndr27** [comment]
having the same issue

**Comment by jonded94** [comment]
This was because of the way that the release of `0.2.1.post1` was done. The only available wheel (https://pypi.org/project/kaleido/0.2.1.post1/#files) is `py2.py3-none-manylinux2014_armv7l` compatible, while wheels of all  other platforms are in version 0.2.1.

Since the only commit between the two different versions is one enabling ARM builds (https://github.com/plotly/Kaleido/compare/v0.2.1...v0.2.1.post1), why not simply push the 0.2.1 wheels into the 0.2.1.post1 release? With the current way, nobody using `poetry` (or other package manager with a proper locking mechanism) can use this project in a platform-independent way because, depending on platform, one has to use either one or the other `kaleido` version.
Or better yet, do a proper 0.2.2 release which contains *all* wheels? This is what basically the entire rest of the Python community is doing. I'm a bit surprised that this can take weeks?

**Comment by carschandler** [comment]
Also an issue using `uv`

**Comment by devnoname120** [comment]
Just pin the version:

```shell
poetry add 'kaleido == 0.2.1'
```

**Comment by axiangcoding** [comment]
Same issue

**Comment by ayjayt** [comment]
These are the old versions of kaleido, and building and pushing them is quite difficult and somewhat a bad idea, it's not longer a viable strategy since the embedded chromium is now gigantic.

A new version was released on 1.0.0rc, but it requires you to manually install chrome, or edge.

The official new release is delayed by about a week (it was meant to come out pre-christmas, but it looks like the end of this week, due to me and the holidays), but it's being beefed up to help debugging and solving these issues.

On top of that, I'm looking at longer term solutions using sciter or kobalt instead of using chrome externally, but thats in idea phase right now.

**Comment by leogaggl** [comment]
Same issue on Ubuntu 24.04LTS - Poetry V2.0.1

**Comment by ayjayt** [comment]
@leogaggl the old versions of kaleido or the release candidates? what verison?

**Comment by leogaggl** [comment]
I just needed to add kaleido as a dependency (since I am generating SVG from plotly).

```
poetry add kaleido
Using version ^0.2.1.post1 for kaleido

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing kaleido (0.2.1.post1): Failed

    | Unable to find installation candidates for kaleido (0.2.1.post1)
    | 
    | This is likely not a Poetry issue.
    | 
    |   - 1 candidate(s) were identified for the package
    |   - 1 wheel(s) were skipped as your project's environment does not support the identified abi tags
    | 
    | Solutions:
    | Make sure the lockfile is up-to-date. You can try one of the following;
    | 
    |     1. Regenerate lockfile: poetry lock --no-cache --regenerate
    |     2. Update package     : poetry update --no-cache kaleido
    | 
    | If neither works, please first check to verify that the kaleido has published wheels available from your configured source that are compatible with your environment- ie. operating system, architecture (x86_64, arm64 etc.), python interpreter.
    | 
    | You can also run your poetry command with -v to see more information.
```

'pip install kaleido' works, but it kinda defeats the purpose of automated dependency management.

I ended up pinning the version (which isn't the desired outcome) as a workaround.

**Comment by ayjayt** [comment]
We're having this issue a lot but yeah, 0.2.1.post1 is an arm32 only release, and 0.2.1 is the everything only release.

I'm struggling with uv and poetry because they should be resolving *the highest version* for the architecture. It would be fine to use 0.2.1.

The situation will be changing somewhat with the new release of kaleido.
