### ISSUE TITLE
successful kaleido tests

### ISSUE THREAD

**Issue by gvwilson** [plotly/Kaleido#213]
Placeholder issue for dtdoctor reports etc. for successful tests of kaleido release candidates.

**Comment by gvwilson** [comment]
received 2024-10-24

```
(.venv) godzilla@leo:~/install/kaleido$ dtdoctor
**************************************************
*****Collecting information about the system:*****
Linux
6.11.0-8-generic
#8-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep 16 13:41:20 UTC 2024
uname_result(system='Linux', node='leo', release='6.11.0-8-generic', version='#8-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep 16 13:41:20 UTC 2024', machine='x86_64')
***************Looking for browser:***************
looking for chrome
looking for None
looking for Chrome
looking for None
looking for google-chrome
looking for /usr/bin/google-chrome
/usr/bin/google-chrome
************Looking for version info:*************
b'choreographer==0.99.1\nkaleido==0.4.0rc1\nnumpy==2.1.2\npackaging==24.1\npandas==2.2.3\nplotly==5.24.1\npython-dateutil==2.9.0.post0\npytz==2024.2\nsix==1.16.0\ntenacity==9.0.0\ntzdata==2024.2\n'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
*************Done with version info.**************
****************Sync test headless****************
DEBUG REPORT:
BROWSER_PATH: /usr/bin/google-chrome
USER_DATA_DIR: /tmp/tmpl1ts6y13
Old Headless mode will be removed from the Chrome binary soon. Please use the new Headless mode (https://developer.chrome.com/docs/chromium/new-headless) or the chrome-headless-shell which is a standalone implementation of the old Headless mode (https://developer.chrome.com/blog/chrome-headless-shell).

[1024/203404.693609:WARNING:vaapi_wrapper.cc(1534)] Skipping nVidia device named: nvidia-drm
[1024/203404.711797:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
[1024/203404.713014:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
write_json:
write_json: {"id": 0, "method": "Browser.close"}
wrote_json.
[1024/203405.288204:ERROR:devtools_pipe_handler.cc(188)] Connection terminated while reading from pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pipe.close() (or slow Browser.close) method closed browser
Tempfile still exists?: False
***********Done with sync test headless***********
***************Async Test headless****************
DEBUG REPORT:
BROWSER_PATH: /usr/bin/google-chrome
USER_DATA_DIR: /tmp/tmpdwpctqd_
read_jsons (blocking):
write_json:
Starting watchdog
write_json: {"id": 0, "method": "Target.getTargets"}
wrote_json.
Old Headless mode will be removed from the Chrome binary soon. Please use the new Headless mode (https://developer.chrome.com/docs/chromium/new-headless) or the chrome-headless-shell which is a standalone implementation of the old Headless mode (https://developer.chrome.com/blog/chrome-headless-shell).

{"id":0,"result":{"targetInfos":[]}}
read_jsons: {'id': 0, 'result': {'targetInfos': []}}
run_read_loop() found future for key ('', 0)
read_jsons (blocking):
[1024/203405.701265:WARNING:vaapi_wrapper.cc(1534)] Skipping nVidia device named: nvidia-drm
[1024/203405.718198:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
[1024/203405.719128:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
is_closed called with wait: 0
write_json:
write_json: {"id": 1, "method": "Browser.close"}
wrote_json.
{"id":1,"result":{}}
read_jsons: {'id': 1, 'result': {}}
run_read_loop() found future for key ('', 1)
is_closed called with wait: 0
read_jsons (blocking):
read_jsons pipe was closed, raising
caught OSError in read() 
PipeClosedError caught
Browser is being closed because chrom* closed
Browser.close method closed browser
Tempfile still exists?: False
**********Done with async test headless***********

Error in: System Info
Traceback (most recent call last):
  File "/home/godzilla/install/kaleido/.venv/lib/python3.12/site-packages/choreographer/browser.py", line 736, in diagnose
    print(subprocess.check_output(["git", "describe", "--all", "--tags", "--long", "--always",]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', '--all', '--tags', '--long', '--always']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/home/godzilla/install/kaleido/.venv/bin/dtdoctor", line 8, in <module>
    sys.exit(diagnose())
             ^^^^^^^^^^
  File "/home/godzilla/install/kaleido/.venv/lib/python3.12/site-packages/choreographer/browser.py", line 777, in diagnose
    raise BaseException("There was an exception, see above.")
BaseException: There was an exception, see above.
```

**Comment by ayjayt** [comment]
https://github.com/plotly/Kaleido/issues/213#issuecomment-2437702863

so this is fine yeah? this is just, there was no git installed.

i can rework dtdoctor for this new phase of testing (where people instally from pypi) but we should move onto enabling debug during kaleido and asking for that instead of using dtdoctor which just does choreographer

**Comment by ayjayt** [comment]
Dead thread
