### ISSUE TITLE
ModuleNotFoundError: No module named 'kaleido.scopes'; 'kaleido' is not a package

### ISSUE THREAD

**Issue by cpsievert** [plotly/Kaleido#97]
I've tried installing with both pip and conda and keep running into this same error 

```shell
$ which python3                                                       
~/opt/anaconda3/bin/python3
```

```shell
$ cat ~/opt/anaconda3/lib/python3.8/site-packages/kaleido/_version.py                 
__version__ = "0.2.1"
```

```python
$ python3
Python 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kaleido.scopes.plotly import PlotlyScope
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cpsievert/github/plotly/kaleido.py", line 1, in <module>
    from kaleido.scopes.plotly import PlotlyScope
ModuleNotFoundError: No module named 'kaleido.scopes'; 'kaleido' is not a package
```

```shell
$ ▶ conda list
# packages in environment at /Users/cpsievert/opt/anaconda3:
#
# Name                    Version                   Build  Channel
...
kaleido                   0.2.1                    pypi_0    pypi
...
```

**Comment by alexcjohnson** [comment]
`File "/Users/cpsievert/github/plotly/kaleido.py"`

Looks like it's trying to import that file as the Kaleido package - can you rename it to something that's not a package name?

**Comment by cpsievert** [comment]
Whoops, nice catch, thanks!
